# Generated by Django 4.1.1 on 2022-10-17 05:32

from django.db import migrations, transaction, IntegrityError
import datetime


def add_times(apps, schema_editor):
    # We can't import the TimeAvailability model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    TimeAvailability = apps.get_model('VandyLifts', 'TimeAvailability')

    DAY_OF_THE_WEEK = {
        '1': 'Monday',
        '2': 'Tuesday',
        '3': 'Wednesday',
        '4': 'Thursday',
        '5': 'Friday',
        '6': 'Saturday',
        '7': 'Sunday',
    }

    # The Rec opens at 6am at the earliest and closes at 11pm at the latest
    OPENING_HOUR = 7
    CLOSING_HOUR = 12 + 11 # This value is an exclusive bound of the range
    MINUTE_INTERVAL = 60

    TIMES_GENERATED = [datetime.time(hour=hour, minute=minute)
                       for hour in range(OPENING_HOUR, CLOSING_HOUR)
                       for minute in range(0, 60, MINUTE_INTERVAL)]

    times = [TimeAvailability(day=day, time=time) for day in DAY_OF_THE_WEEK.keys() for time in TIMES_GENERATED]

    # Attempt to bulk create every time, but if any already exist, fall back to creating each one individually
    # We do this because Oracle does not support ignore_conflicts on bulk_create
    try:
        with transaction.atomic():
            TimeAvailability.objects.bulk_create(times)
    except IntegrityError:
        for time in times:
            try:
                with transaction.atomic():
                    time.save()
            except IntegrityError:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('VandyLifts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_times),
    ]
